# Generated by Django 5.2.2 on 2025-07-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productfeatures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
