# Generated by Django 5.2.2 on 2025-06-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
